services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=''
      - POSTGRES_PASSWORD=''
      - POSTGRES_DB=reddit_rCryptocurrency
    volumes:
      - "./reddit_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - ""
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=''
      - PGADMIN_DEFAULT_PASSWORD=''
    ports:
      - ""
    